AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "bin/*"
    - "**/Rakefile"
    - "**/spec/**/*"
    - "**/db/schema.rb"

# Elmatica preferences

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Lambda:
  EnforcedStyle: literal

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 100

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Lint/UnusedMethodArgument:
  Severity: warning

Lint/EmptyBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

# Cops that conflict with rufo

Layout/AccessModifierIndentation:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/ConditionPosition:
  Enabled: false

Layout/DefEndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBeginBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/AssignmentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationStyle:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAfterMethodName:
  Enabled: false

Layout/SpaceAfterNot:
  Enabled: false

Layout/SpaceAfterSemicolon:
  Enabled: false

Layout/SpaceAroundBlockParameters:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceAroundKeyword:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceBeforeSemicolon:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Layout/SpaceInsideReferenceBrackets:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingMethodEndStatement:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false
